### ISSUE TITLE
Add CORS headers

### ISSUE THREAD

**Issue by jmvanel** [dbpedia/dbpedia-lookup#1]
Here is what I get in Firefox (similar stuff in Chromium):

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://lookup.dbpedia.org/api/search?query=Biology&maxResults=15&format=json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Here is my code with JQuery;
```javascript
var searchServiceURL = "https://lookup.dbpedia.org"
const resultsCount = 15
var stringToSearch = "Biology"
    $.ajax({
        url: searchServiceURL + "?query=" + stringToSearch
                              + "&maxResults=" + resultsCount
                              + "&format=json" ,
        dataType: "json" ,
        timeout: 30000
    }).done( function (ajaxResponse) {
        console.log('Ajax Response from ' + searchServiceURL)
        console.log(ajaxResponse)
        callback( prettyPrintURIsFromDbpediaResponse(ajaxResponse) )
    })```

but it should be the same with old XMLHttpRequest API .

**Remedy**

Add HTTP header:
`Access-Control-Allow-Origin: *`

**Comment by holycrab13** [comment]
Should be fixed, please verify

**Comment by jmvanel** [comment]
Everything looks fine, I close !
```shell
wget --debug 'https://lookup.dbpedia.org/api/search?query=jazz&format=json'
---response begin---
HTTP/1.1 200 
Date: Thu, 24 Sep 2020 10:37:37 GMT
Server: Apache/2.4.38 (Debian)
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET
Access-Control-Max-Age: 1000
Access-Control-Allow-Headers: x-requested-with, Content-Type, origin, authorization, accept, client-security-token
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
---response end---
200 
```

**Comment by jmvanel** [comment]
By curiosity , I looked in commits, and I saw nothing related , at least in the last 4 days ...

**Comment by jmvanel** [comment]
Since a few days the header
`Access-Control-Allow-Origin: *
`
has disappeared, as can be seen by running
`wget --debug 'https://lookup.dbpedia.org/api/search?query=jazz&format=json'
`
I'm aware that this is probably only a deployment issue,
but no support contact is provided on this GitHub project...

**Comment by holycrab13** [comment]
Hi, the deployment has indeed changed and this has been overlooked, sorry!. I will add the CORS header.

**Comment by holycrab13** [comment]
Should be fixed again, mod headers was disabled in the new apache setting

**Comment by jmvanel** [comment]
Indeed , it works again with JavaScript in browser thanks !
I feel that deployment stuff , ideally a shell script , should be part of github project.
