### ISSUE TITLE
Demo Down (lookup.dbpedia.org)

### ISSUE THREAD

**Issue by kmdn** [dbpedia/dbpedia-lookup#15]
Hello there,

Love DBpedia Lookup. I'm actually using as part of my research on entity linking pipelines as one of the interlinking components.

Unfortunately, the DBpedia Lookup demo seems to be down. Are there plans on bringing it back up?

Here a sample query (from https://www.dbpedia.org/resources/lookup-linking/) I tried out and which didn't work:
https://lookup.dbpedia.org/api/search?type=City&query=Berlin

All the best for the project & wishing great end of year!

KMDN

**Comment by Ghostapple** [comment]
I am wondering about this issue, too.

**Comment by sergejsrk** [comment]
Yep. Same here!
