### ISSUE TITLE
A dbo:Species not found with typeName=Species

### ISSUE THREAD

**Issue by jmvanel** [dbpedia/dbpedia-lookup#3]
Looking for "punica" , the pomegranate plant species:

```shell
wget -O - \
  'https://lookup.dbpedia.org/api/search?query=punica&maxResults=15&format=json&typeName=Species'
  | jq .
```
No pomegranate in results. Instead, animals are found :( .
Removing `&typeName=Species` provides pomegranate in first position.
I noticed this for many, if not all, plants.

**Comment by holycrab13** [comment]
I checked the resource http://dbpedia.org/page/Pomegranate
This is a data issue and not a DBpedia Lookup issue: The current extraction wrongly states that the Pomegranate is an Insect! :S

I checked other related resources and realized that there seems to be a bigger issue with Type extraction in the current version of the framework. Please open an issue here: https://github.com/dbpedia/extraction-framework
