### ISSUE TITLE
How to get all data from dbpedia page in a request

### ISSUE THREAD

**Issue by dasisro-trendlab** [dbpedia/dbpedia-lookup#4]
Hello everyone,
I'm trying to get all the data from https://dbpedia.org/page/Asturias (Abstract, Place, Areacode...etc) using python but without success.
I tried with SPARQL (and Python) making some requests and the result was the same. Does someone know if there is a way to get the all data in a request?
Thanks very much in advance,
David

**Comment by mommi84** [comment]
Hi. I think what you're asking for is unrelated to DBpedia Lookup, so you'd better post in the [Forum](https://forum.dbpedia.org/). Anyway, you can simply make the following query to https://dbpedia.org/sparql using SPARQLWrapper or any HTTP library.

`describe dbr:Asturias`

**Comment by edgardmarx** [comment]
Alternatively, you can just change the namespace from https://dbpedia.org/page/Asturias to https://dbpedia.org/data/Asturias.

**Comment by mommi84** [comment]
> Alternatively, you can just change the namespace from https://dbpedia.org/page/Asturias to https://dbpedia.org/data/Asturias.

Correct. The output of this solution will be RDF, so you'll need the Python rdflib library to parse it. You can get JSON output by pointing to https://dbpedia.org/data/Asturias.json

**Comment by dasisro-trendlab** [comment]
Thank you very much for all, I close this, and next time I'll follow your suggestions (@mommi84) put them on the forum.
