### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by InBetweenNames** [dbpedia/dbpedia-lookup#8]
The certificate for the live lookup service seems to have expired.  Any chance we could get an updated cert?

**Comment by InBetweenNames** [comment]
Nevermind, seems to be working now.

**Comment by JJ-Author** [comment]
for some reason it is still an issue for me

**Comment by JJ-Author** [comment]
and there seems no new cert issued https://crt.sh/?q=lookup.dbpedia.org

**Comment by InBetweenNames** [comment]
Yeah, it seems to have started causing problems again here.
